### ISSUE TITLE
hlsrecord won't stop

### ISSUE THREAD

**Issue by spinosae** [kanongil/node-hls-tools#2]
First of all, thanks for the great project. However hlsrecord didn't stop as it should. Here is a sample command: 
node hlsrecord http://live.3gv.ifeng.com/cctv13.m3u8 -e +240 -o cctv13
The recording should stop after 4 minutes, however it didn't.
For your information, I am running newest version of nodeJS on Windows 10 build 10159

**Comment by kanongil** [comment]
Thanks for thumbs up. This is still mostly a personal project, which is why I haven't published it to npm or bothered to make more comprehensive documentation.

The end time option currently only works for streams which embed time information in the m3u8 playlist. I am open to a pull request which can infer such information from live streams, to support this use-case.

**Comment by kanongil** [comment]
Added #3 to track this issue.

**Comment by spinosae** [comment]
Thanks for the quick reply. I ended up using machine time to stop the recording (what a lazy trick). Again thanks for the great project. This is so far the best m3u8 downloader I ever used.

**Comment by spinosae** [comment]
Hi Gil,

We really appreciate your efforts on this. Do you have a rough timeline for this bug/feature to be fixed? Also, we'll be glad to make contributions through PayPal if you want.

Yours Sincerely,

Que Yanghua
